import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-dvh bg-purple-50 px-6 pt-24 antialiased",
          "sm:pt-30",
          inter.className,
        )}
      >
        <main className={"mx-auto max-w-[426px]"}>{children}</main>
      </body>
    </html>
  );
}
